# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import picture_pb2 as picture__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in picture_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PictureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.unary_unary(
                '/PictureService/Upload',
                request_serializer=picture__pb2.UploadRequest.SerializeToString,
                response_deserializer=picture__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/PictureService/Search',
                request_serializer=picture__pb2.SearchRequest.SerializeToString,
                response_deserializer=picture__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Download = channel.unary_unary(
                '/PictureService/Download',
                request_serializer=picture__pb2.DownloadRequest.SerializeToString,
                response_deserializer=picture__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/PictureService/Delete',
                request_serializer=picture__pb2.DeleteRequest.SerializeToString,
                response_deserializer=picture__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Like = channel.unary_unary(
                '/PictureService/Like',
                request_serializer=picture__pb2.LikeRequest.SerializeToString,
                response_deserializer=picture__pb2.LikeResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/PictureService/List',
                request_serializer=picture__pb2.ListRequest.SerializeToString,
                response_deserializer=picture__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/PictureService/Health',
                request_serializer=picture__pb2.HealthRequest.SerializeToString,
                response_deserializer=picture__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.VoteRequest = channel.unary_unary(
                '/PictureService/VoteRequest',
                request_serializer=picture__pb2.VoteArgs.SerializeToString,
                response_deserializer=picture__pb2.VoteReply.FromString,
                _registered_method=True)
        self.GlobalCommit = channel.unary_unary(
                '/PictureService/GlobalCommit',
                request_serializer=picture__pb2.DecisionArgs.SerializeToString,
                response_deserializer=picture__pb2.Ack.FromString,
                _registered_method=True)
        self.GlobalAbort = channel.unary_unary(
                '/PictureService/GlobalAbort',
                request_serializer=picture__pb2.DecisionArgs.SerializeToString,
                response_deserializer=picture__pb2.Ack.FromString,
                _registered_method=True)


class PictureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Like(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteRequest(self, request, context):
        """--- 2PC EXTENSIONS --John Song-//
        Phase 1: Voting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalCommit(self, request, context):
        """Phase 2: Decision
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalAbort(self, request, context):
        """------------------------------//
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PictureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=picture__pb2.UploadRequest.FromString,
                    response_serializer=picture__pb2.UploadResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=picture__pb2.SearchRequest.FromString,
                    response_serializer=picture__pb2.SearchResponse.SerializeToString,
            ),
            'Download': grpc.unary_unary_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=picture__pb2.DownloadRequest.FromString,
                    response_serializer=picture__pb2.DownloadResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=picture__pb2.DeleteRequest.FromString,
                    response_serializer=picture__pb2.DeleteResponse.SerializeToString,
            ),
            'Like': grpc.unary_unary_rpc_method_handler(
                    servicer.Like,
                    request_deserializer=picture__pb2.LikeRequest.FromString,
                    response_serializer=picture__pb2.LikeResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=picture__pb2.ListRequest.FromString,
                    response_serializer=picture__pb2.ListResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=picture__pb2.HealthRequest.FromString,
                    response_serializer=picture__pb2.HealthResponse.SerializeToString,
            ),
            'VoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteRequest,
                    request_deserializer=picture__pb2.VoteArgs.FromString,
                    response_serializer=picture__pb2.VoteReply.SerializeToString,
            ),
            'GlobalCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalCommit,
                    request_deserializer=picture__pb2.DecisionArgs.FromString,
                    response_serializer=picture__pb2.Ack.SerializeToString,
            ),
            'GlobalAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalAbort,
                    request_deserializer=picture__pb2.DecisionArgs.FromString,
                    response_serializer=picture__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PictureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PictureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PictureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/Upload',
            picture__pb2.UploadRequest.SerializeToString,
            picture__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/Search',
            picture__pb2.SearchRequest.SerializeToString,
            picture__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/Download',
            picture__pb2.DownloadRequest.SerializeToString,
            picture__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/Delete',
            picture__pb2.DeleteRequest.SerializeToString,
            picture__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Like(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/Like',
            picture__pb2.LikeRequest.SerializeToString,
            picture__pb2.LikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/List',
            picture__pb2.ListRequest.SerializeToString,
            picture__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/Health',
            picture__pb2.HealthRequest.SerializeToString,
            picture__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/VoteRequest',
            picture__pb2.VoteArgs.SerializeToString,
            picture__pb2.VoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/GlobalCommit',
            picture__pb2.DecisionArgs.SerializeToString,
            picture__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PictureService/GlobalAbort',
            picture__pb2.DecisionArgs.SerializeToString,
            picture__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
