# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: queue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x12\x05queue\"S\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05votes\x18\x04 \x01(\x05\x12\x10\n\x08\x64uration\x18\x05 \x01(\x05\"\x15\n\x07TrackId\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x0bVoteRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02up\x18\x02 \x01(\x08\"(\n\tQueueList\x12\x1b\n\x05queue\x18\x01 \x03(\x0b\x32\x0c.queue.Track\"=\n\rQueueResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1b\n\x05queue\x18\x02 \x03(\x0b\x32\x0c.queue.Track\"\x07\n\x05\x45mpty2\xd9\x02\n\x0cQueueService\x12.\n\x08\x41\x64\x64Track\x12\x0c.queue.Track\x1a\x14.queue.QueueResponse\x12\x33\n\x0bRemoveTrack\x12\x0e.queue.TrackId\x1a\x14.queue.QueueResponse\x12\x35\n\tVoteTrack\x12\x12.queue.VoteRequest\x1a\x14.queue.QueueResponse\x12*\n\x08GetQueue\x12\x0c.queue.Empty\x1a\x10.queue.QueueList\x12+\n\x0bGetMetadata\x12\x0e.queue.TrackId\x1a\x0c.queue.Track\x12&\n\x08PlayNext\x12\x0c.queue.Empty\x1a\x0c.queue.Track\x12,\n\nGetHistory\x12\x0c.queue.Empty\x1a\x10.queue.QueueListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACK']._serialized_start=22
  _globals['_TRACK']._serialized_end=105
  _globals['_TRACKID']._serialized_start=107
  _globals['_TRACKID']._serialized_end=128
  _globals['_VOTEREQUEST']._serialized_start=130
  _globals['_VOTEREQUEST']._serialized_end=167
  _globals['_QUEUELIST']._serialized_start=169
  _globals['_QUEUELIST']._serialized_end=209
  _globals['_QUEUERESPONSE']._serialized_start=211
  _globals['_QUEUERESPONSE']._serialized_end=272
  _globals['_EMPTY']._serialized_start=274
  _globals['_EMPTY']._serialized_end=281
  _globals['_QUEUESERVICE']._serialized_start=284
  _globals['_QUEUESERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
