# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import queue_pb2 as queue__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTrack = channel.unary_unary(
                '/queue.QueueService/AddTrack',
                request_serializer=queue__pb2.Track.SerializeToString,
                response_deserializer=queue__pb2.QueueResponse.FromString,
                _registered_method=True)
        self.RemoveTrack = channel.unary_unary(
                '/queue.QueueService/RemoveTrack',
                request_serializer=queue__pb2.TrackId.SerializeToString,
                response_deserializer=queue__pb2.QueueResponse.FromString,
                _registered_method=True)
        self.VoteTrack = channel.unary_unary(
                '/queue.QueueService/VoteTrack',
                request_serializer=queue__pb2.VoteRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueResponse.FromString,
                _registered_method=True)
        self.GetQueue = channel.unary_unary(
                '/queue.QueueService/GetQueue',
                request_serializer=queue__pb2.Empty.SerializeToString,
                response_deserializer=queue__pb2.QueueList.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/queue.QueueService/GetMetadata',
                request_serializer=queue__pb2.TrackId.SerializeToString,
                response_deserializer=queue__pb2.Track.FromString,
                _registered_method=True)
        self.PlayNext = channel.unary_unary(
                '/queue.QueueService/PlayNext',
                request_serializer=queue__pb2.Empty.SerializeToString,
                response_deserializer=queue__pb2.Track.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/queue.QueueService/GetHistory',
                request_serializer=queue__pb2.Empty.SerializeToString,
                response_deserializer=queue__pb2.QueueList.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTrack,
                    request_deserializer=queue__pb2.Track.FromString,
                    response_serializer=queue__pb2.QueueResponse.SerializeToString,
            ),
            'RemoveTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTrack,
                    request_deserializer=queue__pb2.TrackId.FromString,
                    response_serializer=queue__pb2.QueueResponse.SerializeToString,
            ),
            'VoteTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteTrack,
                    request_deserializer=queue__pb2.VoteRequest.FromString,
                    response_serializer=queue__pb2.QueueResponse.SerializeToString,
            ),
            'GetQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueue,
                    request_deserializer=queue__pb2.Empty.FromString,
                    response_serializer=queue__pb2.QueueList.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=queue__pb2.TrackId.FromString,
                    response_serializer=queue__pb2.Track.SerializeToString,
            ),
            'PlayNext': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayNext,
                    request_deserializer=queue__pb2.Empty.FromString,
                    response_serializer=queue__pb2.Track.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=queue__pb2.Empty.FromString,
                    response_serializer=queue__pb2.QueueList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queue.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('queue.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/AddTrack',
            queue__pb2.Track.SerializeToString,
            queue__pb2.QueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/RemoveTrack',
            queue__pb2.TrackId.SerializeToString,
            queue__pb2.QueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoteTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/VoteTrack',
            queue__pb2.VoteRequest.SerializeToString,
            queue__pb2.QueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/GetQueue',
            queue__pb2.Empty.SerializeToString,
            queue__pb2.QueueList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/GetMetadata',
            queue__pb2.TrackId.SerializeToString,
            queue__pb2.Track.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/PlayNext',
            queue__pb2.Empty.SerializeToString,
            queue__pb2.Track.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/GetHistory',
            queue__pb2.Empty.SerializeToString,
            queue__pb2.QueueList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
